# Generated by Django 5.0 on 2024-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_drink_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
