# Generated by Django 5.0 on 2024-02-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_alter_drink_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/drink_images/defaultt.png', null=True, upload_to='drink_images/'),
        ),
    ]
