# Generated by Django 5.0 on 2024-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_alter_drink_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='drink_images/'),
        ),
    ]
