# Generated by Django 5.0 on 2024-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0011_alter_drink_slug_alter_drink_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
