# Generated by Django 5.0 on 2024-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0012_alter_drink_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='drink_images/'),
        ),
    ]
