# Generated by Django 5.0 on 2024-02-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0014_drink_unique_slug_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
