# Generated by Django 5.0 on 2024-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0015_delete_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
