# Generated by Django 5.0 on 2024-03-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0016_alter_drink_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='author',
        ),
    ]
