# Generated by Django 5.0 on 2024-03-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0019_drink_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={},
        ),
        migrations.AlterModelTable(
            name='drink',
            table=None,
        ),
    ]
