# Generated by Django 5.0 on 2024-03-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0020_alter_drink_options_alter_drink_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drink',
            table='drink',
        ),
    ]
