# Generated by Django 5.0 on 2024-03-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0021_alter_drink_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
