# Generated by Django 5.0 on 2024-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('favourites', models.CharField(max_length=20)),
                ('recent', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
