# Generated by Django 5.0 on 2024-01-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data',
            new_name='date',
        ),
    ]
