# Generated by Django 5.0 on 2024-03-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recents',
            options={},
        ),
    ]
